variables:
  CI_IMAGE: rootlogin/nextcloud
  BUILDX_VER: 0.5.1

stages:
  - environment
  - build
  - push
  - afterwork

before_script:
  - '[ "$CI_COMMIT_REF_SLUG" == "master" ] && export CI_DOCKER_TAG="latest" || export CI_DOCKER_TAG="$CI_COMMIT_REF_SLUG"'
  - 'echo "Using CI_DOCKER_TAG: $CI_DOCKER_TAG"'
  - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_TOKEN"

.updateContainerJob:
  image: docker:latest
  stage: environment
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE-builder:$CI_COMMIT_REF_SLUG || true
    - docker build --cache-from $CI_REGISTRY_IMAGE-builder:$CI_COMMIT_REF_SLUG -t $CI_REGISTRY_IMAGE-builder:$CI_COMMIT_REF_SLUG -f Dockerfile.builder .
    - docker push $CI_REGISTRY_IMAGE-builder:$CI_COMMIT_REF_SLUG
  
updateContainer:
  extends: .updateContainerJob
  only:
    changes:
      - Dockerfile.builder
  
ensureContainer:
  extends: .updateContainerJob
  allow_failure: true
  before_script:
    - "mkdir -p ~/.docker && echo '{\"experimental\": \"enabled\"}' > ~/.docker/config.json"
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    # Skip update container `script` if the container already exists
    # via https://gitlab.com/gitlab-org/gitlab-ce/issues/26866#note_97609397 -> https://stackoverflow.com/a/52077071/796832
    - docker manifest inspect $CI_REGISTRY_IMAGE-builder:$CI_COMMIT_REF_SLUG > /dev/null && exit || true

.buildContainerJob:
  image: $CI_REGISTRY_IMAGE-builder:$CI_COMMIT_REF_SLUG
  stage: build
  services:
    - docker:dind
  before_script:
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use
  retry: 2

build-amd64:
  extends: .buildContainerJob
  script:
    - docker buildx build --push
      --platform linux/amd64
      --build-arg "VCS_REF=$CI_COMMIT_SHORT_SHA" 
      --build-arg 'BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`' 
      -t "$CI_IMAGE:$CI_DOCKER_TAG-amd64" .

build-x86:
  extends: .buildContainerJob
  script:
    - docker buildx build --push
      --platform linux/386
      --build-arg "VCS_REF=$CI_COMMIT_SHORT_SHA" 
      --build-arg 'BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`' 
      -t "$CI_IMAGE:$CI_DOCKER_TAG-x86" .

build-arm64:
  extends: .buildContainerJob
  script:
    - docker buildx build --push
      --platform linux/arm64/v8
      --build-arg "VCS_REF=$CI_COMMIT_SHORT_SHA" 
      --build-arg 'BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`' 
      -t "$CI_IMAGE:$CI_DOCKER_TAG-arm64" .

build-armv7:
  extends: .buildContainerJob
  script:
    - docker buildx build --push
      --platform linux/arm/v7
      --build-arg "VCS_REF=$CI_COMMIT_SHORT_SHA" 
      --build-arg 'BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`' 
      -t "$CI_IMAGE:$CI_DOCKER_TAG-armv7" .

build-ppc64le:
  extends: .buildContainerJob
  script:
    - docker buildx build --push
      --platform linux/ppc64le
      --build-arg "VCS_REF=$CI_COMMIT_SHORT_SHA" 
      --build-arg 'BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`' 
      -t "$CI_IMAGE:$CI_DOCKER_TAG-ppc64le" .

build-s390x:
  extends: .buildContainerJob
  script:
    - docker buildx build --push
      --platform linux/s390x
      --build-arg "VCS_REF=$CI_COMMIT_SHORT_SHA" 
      --build-arg 'BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`' 
      -t "$CI_IMAGE:$CI_DOCKER_TAG-s390x" .

push-docker-hub:
  image: $CI_REGISTRY_IMAGE-builder:$CI_COMMIT_REF_SLUG
  stage: push
  script:
    - docker pull "$CI_IMAGE:$CI_DOCKER_TAG-amd64"
    - docker pull "$CI_IMAGE:$CI_DOCKER_TAG-x86"
    - docker pull "$CI_IMAGE:$CI_DOCKER_TAG-arm64"
    - docker pull "$CI_IMAGE:$CI_DOCKER_TAG-armv7"
    - docker pull "$CI_IMAGE:$CI_DOCKER_TAG-ppc64le"
    - docker pull "$CI_IMAGE:$CI_DOCKER_TAG-s390x"
    - docker manifest create
      "$CI_IMAGE:$CI_DOCKER_TAG"
      --amend "$CI_IMAGE:$CI_DOCKER_TAG-amd64"
      --amend "$CI_IMAGE:$CI_DOCKER_TAG-x86"
      --amend "$CI_IMAGE:$CI_DOCKER_TAG-arm64"
      --amend "$CI_IMAGE:$CI_DOCKER_TAG-armv7"
      --amend "$CI_IMAGE:$CI_DOCKER_TAG-ppc64le"
      --amend "$CI_IMAGE:$CI_DOCKER_TAG-s390x"
    - docker manifest push "$CI_IMAGE:$CI_DOCKER_TAG"

push-quay-io:
  image: $CI_REGISTRY_IMAGE-builder:$CI_COMMIT_REF_SLUG
  stage: push
  script:
    - docker login -u "$QUAYIO_USERNAME" -p "$QUAYIO_TOKEN" quay.io
    # x86
    - docker pull "$CI_IMAGE:$CI_DOCKER_TAG-x86"
    - docker tag "$CI_IMAGE:$CI_DOCKER_TAG-x86" "quay.io/$CI_IMAGE:$CI_DOCKER_TAG-x86"
    - docker push "quay.io/$CI_IMAGE:$CI_DOCKER_TAG-x86"
    # amd64
    - docker pull "$CI_IMAGE:$CI_DOCKER_TAG-amd64"
    - docker tag "$CI_IMAGE:$CI_DOCKER_TAG-amd64" "quay.io/$CI_IMAGE:$CI_DOCKER_TAG-amd64"
    - docker push "quay.io/$CI_IMAGE:$CI_DOCKER_TAG-amd64"
    # arm64
    - docker pull "$CI_IMAGE:$CI_DOCKER_TAG-arm64"
    - docker tag "$CI_IMAGE:$CI_DOCKER_TAG-arm64" "quay.io/$CI_IMAGE:$CI_DOCKER_TAG-arm64"
    - docker push "quay.io/$CI_IMAGE:$CI_DOCKER_TAG-arm64"
    # armv7
    - docker pull "$CI_IMAGE:$CI_DOCKER_TAG-armv7"
    - docker tag "$CI_IMAGE:$CI_DOCKER_TAG-armv7" "quay.io/$CI_IMAGE:$CI_DOCKER_TAG-armv7"
    - docker push "quay.io/$CI_IMAGE:$CI_DOCKER_TAG-armv7"
    # ppc64le
    - docker pull "$CI_IMAGE:$CI_DOCKER_TAG-ppc64le"
    - docker tag "$CI_IMAGE:$CI_DOCKER_TAG-ppc64le" "quay.io/$CI_IMAGE:$CI_DOCKER_TAG-ppc64le"
    - docker push "quay.io/$CI_IMAGE:$CI_DOCKER_TAG-ppc64le"
    # s390x
    - docker pull "$CI_IMAGE:$CI_DOCKER_TAG-s390x"
    - docker tag "$CI_IMAGE:$CI_DOCKER_TAG-s390x" "quay.io/$CI_IMAGE:$CI_DOCKER_TAG-s390x"
    - docker push "quay.io/$CI_IMAGE:$CI_DOCKER_TAG-s390x"
    # Multi-arch manifest
    - docker manifest create
      "quay.io/$CI_IMAGE:$CI_DOCKER_TAG"
      --amend "quay.io/$CI_IMAGE:$CI_DOCKER_TAG-amd64"
      --amend "quay.io/$CI_IMAGE:$CI_DOCKER_TAG-x86"
      --amend "quay.io/$CI_IMAGE:$CI_DOCKER_TAG-arm64"
      --amend "quay.io/$CI_IMAGE:$CI_DOCKER_TAG-armv7"
      --amend "quay.io/$CI_IMAGE:$CI_DOCKER_TAG-ppc64le"
      --amend "quay.io/$CI_IMAGE:$CI_DOCKER_TAG-s390x"
    - docker manifest push "quay.io/$CI_IMAGE:$CI_DOCKER_TAG"

webhook-microbadger:
  image: $CI_REGISTRY_IMAGE-builder:$CI_COMMIT_REF_SLUG
  stage: afterwork
  script:
    - curl -X POST https://hooks.microbadger.com/images/rootlogin/nextcloud/$MICROBADGER_WEBHOOK

webhook-pushover:
  image: $CI_REGISTRY_IMAGE-builder:$CI_COMMIT_REF_SLUG
  stage: afterwork
  script:
    - curl -s 
      --form-string "token=$PUSHOVER_TOKEN" 
      --form-string "user=$PUSHOVER_USER" 
      --form-string "title=GitLab CI" 
      --form-string "message=Image $CI_IMAGE:$CI_DOCKER_TAG has been published!" 
      --form-string "sound=pushover" 
      --form-string "priority=0" 
      https://api.pushover.net/1/messages.jso