stages:
  - build

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

build-amd64:
  image: docker:latest
  stage: build
  script:
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - docker build 
      --build-arg "BASE_ARCH=amd64" 
      --build-arg "VCS_REF=$CI_COMMIT_SHORT_SHA" 
      --build-arg 'BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`' 
      -t "$CI_REGISTRY/rootlogin/nextcloud:$CI_COMMIT_SHORT_SHA-amd64" .
    - docker push "$CI_REGISTRY/rootlogin/nextcloud:$CI_COMMIT_SHORT_SHA-amd64"

build-arm32v7:
  image: docker:latest
  stage: build
  script:
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - docker build 
      --build-arg "BASE_ARCH=arm32v7" 
      --build-arg "VCS_REF=$CI_COMMIT_SHORT_SHA" 
      --build-arg 'BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`' 
      -t "$CI_REGISTRY/rootlogin/nextcloud:$CI_COMMIT_SHORT_SHA-arm32v7" .
    - docker push "$CI_REGISTRY/rootlogin/nextcloud:$CI_COMMIT_SHORT_SHA-arm32v7"