stages:
  - build

services:
  - docker:dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-x86:
  image: docker:latest
  stage: build
  script:
    docker build -t $CI_REGISTRY/rootlogin/nextcloud:$CI_COMMIT_SHORT_SHA-x86 .
    docker push $CI_REGISTRY/rootlogin/nextcloud:$CI_COMMIT_SHORT_SHA-x86