name: docker

on: [ push, pull_request ]

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        run: |
          [ "$CI_COMMIT_REF_SLUG" == "master" ] && export CI_DOCKER_TAG="latest" || export CI_DOCKER_TAG="$CI_COMMIT_REF_SLUG"
          echo "Using CI_DOCKER_TAG: $CI_DOCKER_TAG"

          docker buildx build \
            --platform linux/amd64 \
            --build-arg "VCS_REF=$CI_COMMIT_SHORT_SHA" \
            --build-arg 'BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`' \
            -t "$CI_IMAGE:$CI_DOCKER_TAG-amd64" .

  build-x86:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        run: |
          [ "$CI_COMMIT_REF_SLUG" == "master" ] && export CI_DOCKER_TAG="latest" || export CI_DOCKER_TAG="$CI_COMMIT_REF_SLUG"
          echo "Using CI_DOCKER_TAG: $CI_DOCKER_TAG"

          docker buildx build \
            --platform linux/386 \
            --build-arg "VCS_REF=$CI_COMMIT_SHORT_SHA" \
            --build-arg 'BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`' \
            -t "$CI_IMAGE:$CI_DOCKER_TAG-x86" .

