name: docker

on: [ push, pull_request ]

jobs:
  build-env:
    runs-on: ubuntu-latest
    outputs:
      docker-tag: ${{ steps.docker-tag.outputs.tag }}
    steps:
      - name: Retrieve docker tag
        shell: bash
        run: |
          export BRANCH_NAME=${GITHUB_REF#refs/heads/}

          [ "$BRANCH_NAME" == "master" ] && export DOCKER_TAG="latest" || export DOCKER_TAG="${BRANCH_NAME//[^A-Za-z0-9-]/-}"
          echo "::set-output name=tag::$DOCKER_TAG"
        id: docker-tag

  build-amd64:
    runs-on: ubuntu-latest
    needs: [ build-env ]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        run: |
          docker buildx build --push\
            --platform linux/amd64 \
            --build-arg "VCS_REF=$CI_COMMIT_SHORT_SHA" \
            --build-arg 'BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`' \
            -t "rootlogin/nextcloud:${{ needs.build-env.outputs.docker-tag }}-amd64" .

  build-x86:
    runs-on: ubuntu-latest
    needs: [ build-env ]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        shell: bash
        run: |
          docker buildx build --push \
            --platform linux/386 \
            --build-arg "VCS_REF=$CI_COMMIT_SHORT_SHA" \
            --build-arg 'BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`' \
            -t "rootlogin/nextcloud:${{ needs.build-env.outputs.docker-tag }}-x86" .

  build-armv6:
    runs-on: ubuntu-latest
    needs: [ build-env ]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        shell: bash
        run: |
          docker buildx build --push \
            --platform linux/arm/v6 \
            --build-arg "VCS_REF=$CI_COMMIT_SHORT_SHA" \
            --build-arg 'BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`' \
            -t "rootlogin/nextcloud:${{ needs.build-env.outputs.docker-tag }}-armv6" .

  build-armv7:
    runs-on: ubuntu-latest
    needs: [ build-env ]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        shell: bash
        run: |
          docker buildx build --push \
            --platform linux/arm/v7 \
            --build-arg "VCS_REF=$CI_COMMIT_SHORT_SHA" \
            --build-arg 'BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`' \
            -t "rootlogin/nextcloud:${{ needs.build-env.outputs.docker-tag }}-armv7" .

  build-arm64:
    runs-on: ubuntu-latest
    needs: [ build-env ]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        shell: bash
        run: |
          docker buildx build --push \
            --platform linux/arm64 \
            --build-arg "VCS_REF=$CI_COMMIT_SHORT_SHA" \
            --build-arg 'BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`' \
            -t "rootlogin/nextcloud:${{ needs.build-env.outputs.docker-tag }}-arm64" .

  build-ppc64le:
    runs-on: ubuntu-latest
    needs: [ build-env ]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        shell: bash
        run: |
          docker buildx build --push \
            --platform linux/ppc64le \
            --build-arg "VCS_REF=$CI_COMMIT_SHORT_SHA" \
            --build-arg 'BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`' \
            -t "rootlogin/nextcloud:${{ needs.build-env.outputs.docker-tag }}-ppc64le" .

  build-s390x:
    runs-on: ubuntu-latest
    needs: [ build-env ]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        shell: bash
        run: |
          docker buildx build --push \
            --platform linux/s390x \
            --build-arg "VCS_REF=$CI_COMMIT_SHORT_SHA" \
            --build-arg 'BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`' \
            -t "rootlogin/nextcloud:${{ needs.build-env.outputs.docker-tag }}-s390x" .

  push-docker-hub:
    runs-on: ubuntu-latest
    needs: [ build-env, build-amd64, build-x86, build-armv6, build-armv7, build-arm64, build-ppc64le, build-s390x ]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pull images
        shell: bash
        run: |
          docker pull "rootlogin/nextcloud:${{ needs.build-env.outputs.docker-tag }}-x86"
          docker pull "rootlogin/nextcloud:${{ needs.build-env.outputs.docker-tag }}-amd64"
          docker pull "rootlogin/nextcloud:${{ needs.build-env.outputs.docker-tag }}-armv6"
          docker pull "rootlogin/nextcloud:${{ needs.build-env.outputs.docker-tag }}-armv7"
          docker pull "rootlogin/nextcloud:${{ needs.build-env.outputs.docker-tag }}-arm64"
          docker pull "rootlogin/nextcloud:${{ needs.build-env.outputs.docker-tag }}-ppc64le"
          docker pull "rootlogin/nextcloud:${{ needs.build-env.outputs.docker-tag }}-s390x"
      - name: Create multi-arch manifest
        shell: bash
        run: |
          docker manifest create \
            "rootlogin/nextcloud:${{ needs.build-env.outputs.docker-tag }}" \
            --amend "rootlogin/nextcloud:${{ needs.build-env.outputs.docker-tag }}-x86" \
            --amend "rootlogin/nextcloud:${{ needs.build-env.outputs.docker-tag }}-amd64" \
            --amend "rootlogin/nextcloud:${{ needs.build-env.outputs.docker-tag }}-armv6" \
            --amend "rootlogin/nextcloud:${{ needs.build-env.outputs.docker-tag }}-armv7" \
            --amend "rootlogin/nextcloud:${{ needs.build-env.outputs.docker-tag }}-arm64" \
            --amend "rootlogin/nextcloud:${{ needs.build-env.outputs.docker-tag }}-ppc64le" \
            --amend "rootlogin/nextcloud:${{ needs.build-env.outputs.docker-tag }}-s390x"
      - name: Create multi-arch manifest
        shell: bash
        run: docker manifest push "rootlogin/nextcloud:${{ needs.build-env.outputs.docker-tag }}"


